version: '3'

services:
  igoat_server:
    build: 
      context: ./docker-igoat
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8442:8442"
    environment:
      - MAIN_APP_FILE=igoat_server.rb
    restart: always
